FORMAT: 1A
HOST: https://private-cb421-baeml.apiary-mock.com/

# baeML

API allowing users to retrieve articles from the database and indicate their preferences.

## Login [/api/login]
To retrieve personalized feed
### Login User [POST /api/login]
+ Request (application/json)

        {
            "user_ID": userID, //set user in backend
        }
+ Response 200 (application/json)

    + Body
        
            Ok
        
+ Response 204 (text/plain)

    + Body

            Adding user
            
### First Time Login [POST /api/init]
+ Request (application/json)

        {
            "user_ID": userID, //create new user in db
            "size": profile_pic_size,
            "token": accessToken
        }

+ Response 201 (application/json)
    
    + Body
    
        Ok
        
### Get Data [GET /api/load]
+ Request (application/json)

        {
            "user_ID": userID
        }

+ Response 201 (application/json)
    
    + Body
        {
            "name": name,
            "propic": profilepicurl,
            "articles": [
                { 
                    "title": "Python babby snek languini",
                    "link": "python.org"
                    "summary": "....."
                },
                {...}
                ]
        }

## Article Collection [/api/article]
### Retrieve Article [GET]
+ Request (application/json)

+ Response 201 

### Rate Article [POST /api/article/{user_id}/{article_id}/rate]
+ Request (application/json)

    + Headers
    
    + Body
    
            {
                "rating": rating
            }

+ Response 201 (text/plain)
    
    + Body 
            
            Ok, rating added



### Retrieve Articles List [GET /api/list]
+ Response 200 (application/json)
    + Body
    
            {
                "articles": [
                    {
                        "title": "Why is ReactJS so annoying",
                        "link": "http://link",
                        
                        ...
                    },
                    ...
                ]
            }