# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fbid', models.IntegerField()),
                ('article_name', models.CharField(max_length=45)),
                ('article_id', models.IntegerField()),
                ('article_content', picklefield.fields.PickledObjectField(editable=False)),
                ('user_rating', models.SmallIntegerField()),
                ('article_link', models.URLField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PklModels',
            fields=[
                ('user_fbid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pkl_model', picklefield.fields.PickledObjectField(editable=False)),
                ('user_keywords', picklefield.fields.PickledObjectField(editable=False)),
                ('text_corpus', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.IntegerField()),
                ('article_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_fbid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('propic_link', models.URLField(max_length=400)),
                ('articles', models.TextField(null=True)),
            ],
        ),
    ]
