# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.CharField(default='32432233r', max_length=200),
            preserve_default=False,
        ),
    ]
