# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='init_complete',
            field=models.BooleanField(default=False),
        ),
    ]
