# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_fbid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
