# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170716_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pklmodels',
            name='text_corpus',
            field=models.FileField(upload_to=b'training_data'),
        ),
    ]
