# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170717_0309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='article',
        ),
        migrations.DeleteModel(
            name='Keywords',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
