# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-02 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_users_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PklModels',
            fields=[
                ('user_fbid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pkl_model', models.FileField(upload_to=b'pkl_models/<django.db.models.fields.BigIntegerField>/')),
            ],
        ),
    ]
